# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:8.9.3

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
stages:
  - test
  - deploy


# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache


test:
  stage: test
  script:
    - npm install jovo-cli && npm install jovo-cms-googlesheets --save
    - npm install concurrently
    - npm install wait-on
    - npm run-script run-and-test
  cache:
    paths:
      - node_modules/

deploy:
  stage: deploy
  only:
    - master
  script:
    - apt-get update # required to install zip
    # - apt-get -y install python-dev
    # - apt-get -y install python-pip
    # - pip install boto3==1.3.0 # required for lambda_deploy.py
    # # package up the function for deployment
    # # Be sure to change the arguments to your function files
    # - npm install
    # - npm install gulp --save-dev
    # - npm install -g jovo-cli
    # - npm install jovo-framework
    # - npm install firebase-admin
    # - npm run bundle
    # - python lambda_deploy.py
